student/urls.py
from django.urls import path

from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import staticfiles


urlpatterns = [
    #首頁標籤
    path('License-pass', views.Home.as_view(), name='Home'),
    path('GetEntityPaper', views.GetEntityPaper.as_view(), name='GetEntityPaper'),
    path('ReturnEntityPaper', views.ReturnEntityPaper.as_view(), name='ReturnEntityPaper'),
    #登入、登出、個人資訊
    path('login', views.LoginView.as_view(), name='login'),
    path('logout', views.LogoutView.as_view(), name='logout'),
    path('Signin', views.Signin.as_view(), name='Signin'),#註冊
    path('EditPassword/<int:pk>', views.EditPassword.as_view(), name='EditPassword'),#編輯密碼
    path('ForgetPassword', views.ForgetPassword.as_view(), name='ForgetPassword'),
    #系助教端
    path('ImportAndExport', views.ImportAndExport.as_view(), name = 'ImportAndExport'),#匯入匯出
    #path('CheckLicense', views.CheckLicense.as_view(), name='CheckLicense'),#證照瀏覽
    path('DisplayLicense', views.DisplayLicense.as_view(), name='DisplayLicense'),#證照瀏覽
    path('DisplayProject', views.DisplayProject.as_view(), name='DisplayProject'),#報告書瀏覽
    path('DisplayProposal', views.DisplayProposal.as_view(), name='DisplayProposal'),#計畫發表瀏覽
    path('DisplayFinal', views.DisplayFinal.as_view(), name='DisplayFinal'),#學位考試瀏覽
    path('EditStudentDoc/<int:pk>', views.EditStudentDoc.as_view(), name='EditStudentDoc'),
    path('ChangeStudentDocState/<int:pk>/<int:choice>', views.EditStudentDoc.ChangeStudentDocState, name='ChangeStudentDocState'),
    path('AuditLicense/<int:pk>', views.AuditLicense.as_view(), name='AuditLicense'),#審核
    path('SearchStudent', views.SearchStudent.as_view(), name='SearchStudent'),#尋找特定學生
    path('ModifyStudentInfo/<int:pk>', views.ModifyStudentInfo.as_view(), name='ModifyStudentInfo'),#修改學生資料
    path('DeleteStudentInfo/<int:pk>', views.ModifyStudentInfo.deleteStudent, name='DeleteStudent'),#刪除使用者
    path('BookingList', views.BookingList.as_view(), name='BookingList'),#借用申請表
    path('HistoryBookingAnalysis', views.HistoryBookingAnalysis.as_view(), name='HistoryBookingAnalysis'),#歷史借閱分析
    path('HistoryPaperUpdate', views.HistoryPaperUpdate.as_view(), name='HistoryPaperUpdate'),#補回歷年報告書
    #學士
    path('PassProject/<int:pk>', views.PassProject.as_view(), name='PassProject'), #專題繳交
    path('PassLicense/<int:pk>', views.PassLicense.as_view(), name='PassLicense'), #證照繳交
    path('UserProject/<int:pk>', views.UserProject.as_view(), name='UserProject'),#已繳交的專題
    path('UserLicense/<int:pk>', views.UserLicense.as_view(), name='UserLicense'),#已繳交的證照
    path('EditLicense/<int:pk>', views.EditLicense.as_view(), name='EditLicense'),#編輯證照
    path('EditProject/<int:pk>', views.EditProject.as_view(), name='EditProject'),#編輯專題
    path('DeleteLicense/<int:pk>', views.DeleteLicense.as_view(), name='DeleteLicense'),#刪除已繳交的證照
    #碩士
    path('PassProposal/<int:pk>', views.PassProposal.as_view(), name='PassProposal'), #計畫發表
    path('EditProposal/<int:pk>', views.EditProposal.as_view(), name='EditProposal'),#編輯已繳交的計畫發表
    path('PassFinal/<int:pk>', views.PassFinal.as_view(), name='PassFinal'),#學位考試
    path('EditFinal/<int:pk>', views.EditFinal.as_view(), name='EditFinal'),#編輯已繳交的學位考試
    path('UserProposalAndFinal/<int:pk>', views.UserProposalAndFinal.as_view(), name='UserProposalAndFinal'),#已繳交的計畫發表與學位考試歷程
    path('UploadCancel/<str:pk>', views.UploadCancel.as_view(), name="UploadCancel"),#取消申請表上傳
    #學生共用
    path('BorrowPaper/<int:pk>', views.BorrowPaper.as_view(), name='BorrowPaper'),#報告書列表
    path('MakeBooking/<int:pk>', views.BorrowPaper.MakeBooking, name='MakeBooking'),#借用表單
    path('UserBooking/<int:pk>', views.UserBooking.as_view(), name='UserBooking'),#已預約清單
    path('DeleteBooking/<int:pk>', views.UserBooking.deleteBooking, name='DeleteBooking'),#刪除預約  
]

website/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.views.generic.base import TemplateView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('student.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='Home.html'))
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

student/models.py
from time import time
from datetime import date
from django.db import models
from django.contrib import admin
from decimal import Decimal
from django.utils import timezone
from django.contrib.auth.models import AbstractUser
from django import forms
import datetime, os

# Create your models here.

class User(AbstractUser):
    first_name = None
    last_name = None

    username = models.CharField(max_length=15, unique=True, null=True) #帳號
    name = models.CharField(max_length = 12) #姓名

    DEPARTMENT = ((0, '資訊科學系'),
                  (1, '外系'),)
    department = models.IntegerField(choices=DEPARTMENT, null=True, blank=True)

    IDENTITY=((0, '大學部'),
              (1, '管理員'),
              (2, '日間碩士班'),
              (3, '碩士在職專班'),
              (4, '系辦工讀生'))
    identity = models.IntegerField(choices=IDENTITY, default=0)
    enrollYear = models.DecimalField(max_digits = 4, decimal_places = 0, default = timezone.now().year)#入學年

    USER_NAME_FIELD = 'username'

    class Meta:
        ordering = ["username"]

    def __str__(self):
        return self.username

    def not_graduated(self):
        return self.enrollYear + 6 >= timezone.now().year

    def get_enrollYear(self):
        return (self.enrollYear - 1911)

class License(models.Model):
    user = models.ForeignKey(User, null = True, on_delete=models.PROTECT)
    name = models.CharField(max_length = 30) #證照名稱
    acqDate = models.DateField(default=timezone.now)#證照取得日期
    organizer = models.CharField(max_length = 30)#主辦單位

    LEVEL = (('A', 'A'),
             ('B', 'B',))
    level = models.CharField(max_length = 1, choices = LEVEL, default = 0)

    PASS = ((0, '審核中'),
            (1, '通過'),
            (2, '未通過'),)#審核狀態

    pazz = models.IntegerField(choices = PASS, default = 0)#證照是否通過審核
    image = models.ImageField(upload_to='image/', blank=False, null=False, default=None)

    class Meta:
        ordering = ["user__username", "level"]

    def __str__(self):
        return self.name

class Proposal(models.Model):
    user = models.ForeignKey(User, null = True, on_delete=models.PROTECT)
    name = models.CharField(max_length = 30) #論文名稱
    professor = models.CharField(max_length = 5)#指導教授
    postDate = models.DateField(blank=True, null = True)#發表日期
    STATE = ((0, '已申請'),
             (1, '已取消'),)
    state = models.IntegerField(choices=STATE, default = 0)
    cancelapplication = models.FileField(upload_to="CancelProposal/", blank=True, null=True, default=None)
    
    def __str__(self):
        return self.name
    
class Project(models.Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT) #誰做這個專題的
    proposal = models.ForeignKey(Proposal, on_delete=models.PROTECT, blank = True, null = True)
    name = models.CharField(max_length = 30) #專題名稱
    report = models.FileField(upload_to = "Report/", default=None)#報告書電子檔
    poster = models.ImageField(upload_to = "Poster/", default=None)#海報或發表證明
    professor = models.CharField(max_length = 5)#指導教授
    
    FIELD = ((0, '軟體開發及程式設計'),
             (1, '網路及多媒體應用'),
             (2, '系統及演算法開發',))
    field = models.IntegerField(choices=FIELD, default=0)

    postDate = models.DateField(blank=True, null = True)#學位考試日期
    letter = models.FileField(upload_to='Uploaded Files/', blank=True, null=True, default=None)#同意函

    #研討會或期刊
    POST = ((0, '研討會'),
            (1, '期刊'),)
    post = models.PositiveIntegerField(choices=POST, default = 0, blank=True, null = True)
    seminarDate = models.DateTimeField(blank=True, null = True)#研討會或期刊發行日期
    seminarName = models.CharField(max_length=20, blank=True, null = True)#研討會或期刊名稱
    journalNumber = models.DecimalField(max_digits = 10, decimal_places = 0, blank=True, null = True)#期刊刊號
    
    STATE = ((0, '專題'),
             (1, '已申請'),
             (2, '已取消'),)
    state = models.IntegerField(choices=STATE, default = 0)
    cancelapplication = models.FileField(upload_to='CancelFinal/', blank=True, null=True, default=None)
    selected = models.BooleanField(default=False)

    class Meta:
        ordering = ["user"]

    def __str__(self):
        return self.name
    
class Paper(models.Model):
    project = models.ForeignKey(Project, null = True, on_delete=models.CASCADE)
    barCode = models.CharField(max_length=20, null=True)
    lendTimes = models.IntegerField(default=0)


    def __str__(self):
        return self.barCode
    
    def checkPaperBorrowed(self):
        return self.lendTimes > 0

    class Meta:
        ordering = ['barCode', 'project__user__identity']

class Year(models.Model):
    year = models.IntegerField(null = True, blank = True)

    def __str__(self):
        return str(self.year)
    
    class Meta:
        ordering = ['year']

class Booking(models.Model):
    user = models.ForeignKey(User, null = True, on_delete=models.PROTECT)
    paper = models.ForeignKey(Paper, null = True, on_delete=models.PROTECT)
    year = models.ForeignKey(Year,null = True, blank = True, on_delete=models.PROTECT)

    underTaker = models.CharField(null = True, blank = True, max_length=10)
    
    STATE = ((0, '已預約'),
             (1, '已借閱'),
             (2, '已歸還'))
    state = models.IntegerField(choices = STATE, default = 0)
    bookingDate = models.DateTimeField(null = True,)
    takingDate = models.DateTimeField(null = True, blank = True)

    
    def __str__(self):
        return self.user.name
    
    class Meta:
        ordering = ['state', '-id']

class StudentDoc(models.Model):
    qualifiedId = models.BooleanField(default=False)   #考試合格證明
    evaluationForm = models.BooleanField(default=False)  #碩士學位論文評分表
    assesmentResult = models.BooleanField(default=False)  #碩士論文發表會綜合評審結果
    confirmation = models.BooleanField(default=False)  #論文修正確認書

    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.name

templates/AuditLicense.html
{% extends 'layout.html' %}
{% block title %}{{ license.name }}{% endblock %}

{% block content %}
    <div class="container" style="display: flex">
        <form method="POST" action="">
        {% csrf_token %}
            <div class="container" style="flex: 1;">
                {{ form.as_p }}
                <input type="submit" class="btn btn-primary" value="通過" name="pazz">
                <input type="submit" class="btn btn-danger" value="未通過" name="fail">
            </div>
        </form>
        <div class="container" style="flex: 1;">
            <a href="{{ license.image.url }}" target="picture">
                <img src="{{ license.image.url }}" style="width: 100%; height: 100%; cursor: zoom-in; max-width: 1000px; max-height: 600px">
            </a>
        </div>
    </div>
{% endblock %}

templates/DisplayFinal.html
{% extends "layout.html" %}
{% block title %}學位考試總覽{% endblock %}

{% block content %}

<form method = 'POST'>
    {% csrf_token %}
    姓名:<input type = "search" name = "username" placeholder = "" style="width: 150px;">
    指導教授:<input type = "search" name = "professor" placeholder = "" style="width: 150px;">
    入學年:<input type = "search" name = "enrollYear" placeholder="">
    學制:
    <select class = "select" name = "type">
        <option></option>
        <option value = '2' {% if level == '1' %} selected="selected" {% endif %}>日間碩士班</option>
        <option value = '3' {% if level == '2' %} selected="selected" {% endif %}>碩士在職專班</option>
    </select>
    <input type="submit" class="btn btn-primary" name = "search" value="查詢" />
    <input type="submit" class="btn btn-primary" name = "export" value="匯出" />
    <input type="submit" class="btn btn-primary" name = "download" value="全部下載" />
</form>
    <div class="container">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">姓名</th>
                    <th scope="col">學號</th>
                    <th scope="col">學制</th>
                    <th scope="col">指導教授</th>
                    <th scope="col">入學年</th>
                    <th scope="col">學位考試題目</th>
                    <th scope="col">狀態</th>
                    <th scope="col">取消申請表</th>
                    <th scope="col">資料繳交</th>
                </tr>
            </thead>
            <tbody>
                {% for project in project %}
                    <tr>
                        <td>{{ project.user.name }}</td>
                        <td>{{ project.user.username }}</td>
                        <td>{{ project.user.get_identity_display }}</td>
                        <td>{{ project.professor }}</td>
                        <td>{{ project.user.get_enrollYear }}</td>
                        <td>{{ project.name }}</td>
                        {% if project.state == 1 %}
                            <td><button class="btn btn-primary">{{ project.get_state_display }}</button></td>
                            <td></td>
                        {% elif project.state == 2 %}
                            <td><button class="btn btn-danger">{{ project.get_state_display }}</button></td>
                            <td><a href="{{ project.cancelapplication.url }}" target="_blank" class="btn btn-warning">下載</a></td>
                        {% endif %}
                        <td><a href="{% url 'EditStudentDoc' pk=project.user.id %}" class="btn btn-primary">編輯</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <p style="text-align:center">
        {% for page_number in project.paginator.page_range %}
          {% ifequal page_number  project.number %}
            <button class="btn btn-outline-primary">{{ page_number }}</button>
          {% else %}
            <a href="?page={{ page_number }}" class="btn btn-primary">{{ page_number }}</a>
          {% endifequal %}
        {% endfor %}
    </p>
{% endblock %}

templates/DisplayProposal.html
{% extends "layout.html" %}
{% block title %}計畫發表總覽{% endblock %}

{% block content %}

<form method = 'POST'>
    {% csrf_token %}
    姓名:<input type = "search" name = "username" placeholder = "" style="width: 150px;">
    指導教授:<input type = "search" name = "professor" placeholder = "" style="width: 150px;">
    入學年:<input type = "search" name = "enrollYear" placeholder="">
    學制:
    <select class = "select" name = "type">
        <option></option>
        <option value = '2' {% if level == '1' %} selected="selected" {% endif %}>日間碩士班</option>
        <option value = '3' {% if level == '2' %} selected="selected" {% endif %}>碩士在職專班</option>
    </select>
    <input type="submit" class="btn btn-primary" name = "search" value="查詢" />
    <input type="submit" class="btn btn-primary" name = "export" value="匯出" />
    <input type="submit" class="btn btn-primary" name = "download" value="全部下載" />
</form>
    <div class="container">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">姓名</th>
                    <th scope="col">學號</th>
                    <th scope="col">學制</th>
                    <th scope="col">指導教授</th>
                    <th scope="col">入學年</th>
                    <th scope="col">計畫發表題目</th>
                    <th scope="col">狀態</th>
                    <th scope="col">取消申請表</th>
                </tr>
            </thead>
            <tbody>
                {% for proposal in proposal %}
                    <tr>
                        <td>{{ proposal.user.name }}</td>
                        <td>{{ proposal.user.username }}</td>
                        <td>{{ proposal.user.get_identity_display }}</td>
                        <td>{{ proposal.professor }}</td>
                        <td>{{ proposal.user.get_enrollYear }}</td>
                        <td>{{ proposal.name}}</td>
                        {% if proposal.state == 0 %}
                            <td><button class="btn btn-primary">{{ proposal.get_state_display }}</button></td>
                        {% else %}
                            <td><button class="btn btn-danger">{{ proposal.get_state_display }}</button></td>
                            <td><a href="{{ proposal.cancelapplication.url }}" target="_blank" class="btn btn-warning">下載</a></td>
                        {% endif %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <p style="text-align:center">
        {% for page_number in project.paginator.page_range %}
          {% ifequal page_number  project.number %}
            <button class="btn btn-outline-primary">{{ page_number }}</button>
          {% else %}
            <a href="?page={{ page_number }}" class="btn btn-primary">{{ page_number }}</a>
          {% endifequal %}
        {% endfor %}
    </p>
{% endblock %}

templates/EditFinal.html
{% extends 'layout.html' %}
{% block title %}編輯{{ project.name }}(未更動項目不須重新上傳檔案){% endblock %}

{% block content %}
<form method="POST" action="">
    {% csrf_token %}
    <div class="container">
        {{ form.as_p }}
        <input type="submit" class = "btn btn-primary" value="儲存"><br>
    </div>
</form>
{% endblock %}

templates/EditLicense.html
{% extends 'layout.html' %}
{% block title %}{{ license.name }}{% endblock %}

{% block content %}
    <div class="container" style="display: flex">
        <form method="POST" action="">
        {% csrf_token %}
            <div class="container" style="flex: 1;">
                {{ form.as_p }}
                <input type="submit" class="btn btn-primary" value="儲存">
            </div>
        </form>
        <div class="container" style="flex: 1;">
            <a href="{{ license.image.url }}" target="picture">
                <img src="{{ license.image.url }}" style="width: 120%; height: 120%; cursor: zoom-in; max-width: 600px; max-height: 400px">
            </a>
        </div>
    </div>
{% endblock %}

templates/EditProject.html
{% extends 'layout.html' %}
{% block title %}{{ project.name }}{% endblock %}

{% block content %}
<form method="POST" action="">
    {% csrf_token %}
    <div class="container">
        {{ form.as_p }}
        <input type="submit" class = "btn btn-primary" value="儲存"><br>
    </div>
</form>
{% endblock %}

templates/EditProposal.html
{% extends 'layout.html' %}
{% block title %}編輯{{ proposal.name }}(未更動項目不需重新上傳){% endblock %}

{% block content %}
<form method="POST" action="">
    {% csrf_token %}
    <div class="container">
        {{ form.as_p }}
        <input type="submit" class = "btn btn-primary" value="儲存"><br>
    </div>
</form>
{% endblock %}

templates/ImportAndExport.html
{% extends "layout.html" %}
{% block title %}
<div style="background-color:#FFFF37; padding: 5px; border-radius: 5px;"></span>
    新增學生
</div>
{% endblock %}

{% block content %}
<div class="continer"> 
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
 
    <div class="row">
        <div class="col-md-6 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>新增多個學生</h2>
            
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
 
                <div class="col-md-8 col-sm-12 col-xs-12 form-group">
                 
                </label>               
                </div>
               
                    <input type="file" name="myfile" class="form-control"><br/>
                    <button type="submit" class="btn btn-outline-primary" name="multi" value="user">上傳</button>                            
                    <br/>
                </div>
            </div>
        </div>
    </div>
    </form>
    <hr>
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="row">
        <div class="col-md-6 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>新增單個學生</h2>
            
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
 
                <div class="col-md-8 col-sm-12 col-xs-12 form-group">
                 
                </label>               
                </div>
               
                    學號:<input type="text" name="username" class="form-control"><br/>
                    密碼:<input type="password" name="password" class="form-control"><br/>
                    姓名:<input type="text" name="name" class="form-control"><br/>
                    email:<input type="text" name="email" class="form-control"><br/>
                    <button type="submit" class="btn btn-outline-primary" name="single" value="user">新增</button>                            
                    <br/>
                </div>
            </div>
        </div>
    </div>
    <div>

    </div>    
    </form>
</div>
    
{% endblock %}

templates/PassProject.html
{% extends "layout.html" %}
{% block title %}專題繳交{% endblock %}

{% block content %}
    <form action="" enctype="multipart/form-data" method="POST">
        {% csrf_token %}<br>
        <div class = "form-row">
            <div class="form-group col-md-4">     
            </div>
            <div class="form-group col-md-4">
                {{ form.as_p }}
            </div>
            <div class="form-group col-md-4">
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-4">
            </div>
            <div class="form-group col-md-4">
                <input class="btn btn-primary" type="submit" value="上傳">
            </div>
            <div class="form-group col-md-4">
            </div>
        </div>
{% endblock %}

templates/ReturnEntityPaper.html
{% extends 'layout.html' %}

{% block title %}歸還專題報告書/論文{% endblock %}

{% block content %}
    <div class="container"><br>
        <form method="POST" action="" id="barCodeForm">
            {% csrf_token %}
            承辦人(輸入姓名):<input type="text" name="underTaker" id="underTaker" class = "form-control"></br>
            掃描報告書條碼:<input type="text" name="barCode" id="barCode" class="form-control"></br>
            <input type="submit" class="btn btn-primary" value="歸還"></input><br><hr>
        </form>
        <script>
            const barCodeInput = document.getElementById('barCode');
            const barCodeForm = document.getElementById('barCodeForm');
        
            barCodeInput.addEventListener('blur', event => {
                if(barCodeInput.length == 15){
                    barcodeForm.submit();
                }
            });
        </script>
    </div>


{% endblock %}

templates/UserBooking.html
{% extends 'layout.html' %}

{% block title %}我的預約{% endblock %}

{% block content %}
<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">作者</th>
                <th scope="col">專題報告書/論文名稱</th>
                <th scope="col">條碼</th>
                <th scope="col">指導教授</th>
                <th scope="col">領域</th>
                <th scope="col">預約日期</th>
                <th scope="col">預約狀況</th>
                <th scope="col">取消預約</th>
            </tr>
        </thead>
        <tbody>
            {% for booking in booking %}
                <tr>
                    <td>{{ booking.paper.project.user.name }}</td>
                    <td>{{ booking.paper.project.name }}</td>
                    <td>{{ booking.paper.barCode }}</td>
                    <td>{{ booking.paper.project.professor }}</td>
                    <td>{{ booking.paper.project.get_field_display }}</td>
                    <td>{{ booking.bookingDate | date:'Y-m-d H:i' }}</td>
                    {% if booking.state == 0 %}
                        <td><button class="btn btn-outline-primary" disabled>{{ booking.get_state_display }}</button></td>
                    {% elif booking.state == 1 %}
                        <td><button class="btn btn-warning" disabled>{{ booking.get_state_display }}</button></td>
                    {% else %}
                        <td><button class="btn btn-primary" disabled>{{ booking.get_state_display }}</button></td>
                    {% endif %}
                    {% if booking.state == 0 %}
                        <td><a href="{% url 'DeleteBooking' pk=booking.id %}" class="btn btn-danger">取消</a></td>
                    {% endif %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<p style="text-align:center">
    {% for page_number in booking.paginator.page_range %}
      {% ifequal page_number  booking.number %}
        <button class="btn btn-outline-primary">{{ page_number }}</button>
      {% else %}
        <a href="?page={{ page_number }}" class="btn btn-primary">{{ page_number }}</a>
      {% endifequal %}
    {% endfor %}
</p>
{% endblock %}

templates/UserLicense.html
{% extends "layout.html" %}
{% block title %}已上傳的證照{% endblock %}

{% block content %}
    <div class="container">
        <table class="table">
            <thead>
                <th>證照名稱</th>
                <th>證照級別</th>
                <th>取得日期</th>
                <th>審核</th>
                <th></th>
            </thead>
            <tbody>
                {% for license in license %}
                <tr>
                    <td>{{ license.name }}</td>
                    <td>{{ license.level }}</td>
                    <td>{{ license.acqDate }}</td>
                    {% if license.pazz == 0 %}
                    <td><button class="btn btn-outline-primary" disabled>審核中</td>
                        <td><a href="{% url 'EditLicense' pk=license.id %}" class="btn btn-primary">編輯</a></td>
                    {% elif license.pazz == 2 %}
                        <td><button class="btn btn-danger">未通過</td>
                        <td><a href="{% url 'DeleteLicense' pk=license.id %}" class="btn btn-danger">刪除</a></td>
                    {% else %}
                        <td><button class="btn btn-primary">通過</td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/UserProject.html
{% extends "layout.html" %}
{% block title %}已上傳的專題檔案{% endblock %}

{% block content %}
    <div class="container">
        <table class="table">
            <thead>
                <th>專題名稱</th>
                <th>指導教授</th>
                <th>檔案</th>
                <th></th>
            </thead>
            <tbody>
                {% for project in project %}
                <tr>
                    <td>{{ project.name }}</td>
                    <td>{{ project.professor }}</td>
                    <td>{{ project.report }}</td>
                    <td><a href="{% url 'EditProject' pk=project.id%}" class="btn btn-primary">編輯</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}